/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sclr_core_strategy_L2NormFastWrapper */

#ifndef _Included_sclr_core_strategy_L2NormFastWrapper
#define _Included_sclr_core_strategy_L2NormFastWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sclr_core_strategy_L2NormFastWrapper
 * Method:    prepare
 * Signature: (Lsclr/core/database/Dataset;Ljava/lang/String;IDDII)I
 */
JNIEXPORT jint JNICALL Java_sclr_core_strategy_L2NormFastWrapper_prepare
  (JNIEnv *, jobject, jobject, jstring, jint, jdouble, jdouble, jint, jint);

/*
 * Class:     sclr_core_strategy_L2NormFastWrapper
 * Method:    run
 * Signature: (Lsclr/core/Messages/Work;)Lsclr/core/database/Result;
 */
JNIEXPORT jobject JNICALL Java_sclr_core_strategy_L2NormFastWrapper_run
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
