---
apiVersion: v1
kind: Service
metadata:
  name: compute-service
  labels:
    name: compute-service
    app: sclr
spec:
  clusterIP: None
  ports:
  - port: 2551
    protocol: TCP
    targetPort: 2551
  selector:
    name: compute-service
    app: sclr
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: compute
spec:
  selector:
    matchLabels:
      name: compute
      app: sclr
  serviceName: sclr-service
  podManagementPolicy: Parallel
  replicas: 2
  template:
    metadata:
      labels:
        name: compute
        app: sclr
    spec:
      containers:
      - name: compute
        image: us.gcr.io/sclr-akka/compute:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 2551
          name: akka-remote
        resources:
          limits:
            cpu: 250m
            memory: 384Mi
          requests:
            cpu: 250m
            memory: 384Mi
        env:
        - name: AKKA_REMOTING_BIND_PORT
          value: '2551'
        - name: AKKA_REMOTING_BIND_HOST
          value: "$HOSTNAME.sclr.default.svc.cluster.local"
        - name: AKKA_SEED_NODES
          value: 'compute-0.sclr.default.svc.cluster.local:2551'
        - name: CLUSTER_MEMBERSHIP_ASK_TIMEOUT
          value: '5000'
        - name: DATABASE_HOST
          value: sclr-mysql
        - name: DATABASE_USERNAME
          value: 'root'
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: password
        readinessProbe:
          tcpSocket:
            port: 2551
          initialDelaySeconds: 30
          timeoutSeconds: 30
