---
apiVersion: v1
kind: Service
metadata:
  name: compute-service
  labels:
    name: compute-service
    app: sclr
spec:
  clusterIP: None
  ports:
  - port: 2551
    protocol: TCP
    targetPort: 2551
  selector:
    name: compute

---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: compute
spec:
  replicas: 2
  selector:
    matchLabels:
      name: compute
      app: sclr
  serviceName: compute-service
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        name: compute
        app: sclr
    spec:
      containers:
      - name: compute
        image: us.gcr.io/sclr-akka/compute:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 2551
        env:
        - name: DATABASE_HOST
          value: sclr-mysql
        - name: DATABASE_USERNAME
          value: 'root'
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: password
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: FQDN
          value: "compute-service.default.svc.cluster.local"
        - name: AKKA_REMOTING_BIND_HOST
          value: "$(POD_NAME).$(FQDN)"
        - name: AKKA_REMOTING_BIND_PORT
          value: '2551'
        - name: AKKA_SEED_NODE
          value: 'akka.tcp://sclr@compute-0.$(FQDN):2551'
