---
apiVersion: v1
kind: Service
metadata:
  name: compute-service
  labels:
    name: compute-service
    app: sclr
spec:
  clusterIP: None
  ports:
  - protocol: TCP
    name: akka-remote
    port: 2551
    targetPort: 2551
  selector:
    name: compute

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: compute
spec:
  replicas: 1
  selector:
    matchLabels:
      name: compute
      app: sclr
  serviceName: compute-service
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        name: compute
        app: sclr
    spec:
      containers:
      - name: compute
        image: us.gcr.io/sclr-01/sclr:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 2551
          name: akka-remote
        resources:
          limits:
            cpu: 1000m
            memory: 4G
          requests:
            cpu: 900m
            memory: 3.5G
        env:
        - name: DATABASE_HOST
          value: mysql-service
        - name: DATABASE_USERNAME
          value: 'root'
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: password
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: AKKA_REMOTING_BIND_HOST
          value: '$(POD_NAME).compute-service.default.svc.cluster.local'
        - name: AKKA_REMOTING_BIND_PORT
          value: '2551'
        - name: AKKA_SEED_NODES.0
          value: 'akka.tcp://sclr@manage-service.default.svc.cluster.local:2551'
        - name: AKKA_SEED_NODES.1
          value: 'akka.tcp://sclr@compute-0.compute-service.default.svc.cluster.local:2551'
        - name: AKKA_CLUSTER_ROLES.0
          value: 'compute'
        - name: DNS_RESOLVER
          value: 'async-dns'
        - name: RESOLVE_SRV
          value: 'true'
        - name: RESOLV_CONF
          value: 'on'
