---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: compute
spec:
  selector:
    matchLabels:
      name: compute
      tier: akka
      app: sclr
  serviceName: akka-remote
  podManagementPolicy: Parallel
  replicas: 2
  template:
    metadata:
      labels:
        name: compute
        tier: akka
        app: sclr
    spec:
      containers:
      - name: compute
        image: us.gcr.io/sclr-akka/compute:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 2551
          name: akka-remote
#        resources:
#          limits:
#            cpu: 250m
#            memory: 384Mi
#          requests:
#            cpu: 250m
#            memory: 384Mi
        env:
        - name: DATABASE_HOST
          value: sclr-mysql
        - name: DATABASE_USERNAME
          value: 'root'
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: password
#        - name: AKKA_REMOTING_BIND_HOST
#          value: ".local"
#        - name: AKKA_REMOTING_BIND_PORT
#          value: '2551'
#        - name: AKKA_SEED_NODE_0
#          value: 'akka.tcp://sclr@compute-0.local:2551'
#        - name: AKKA_SEED_NODE_1
#          value: 'akka.tcp://sclr@compute-0.local:2552'
#        - name: CLUSTER_MEMBERSHIP_ASK_TIMEOUT
#          value: '5000'
#        readinessProbe:
#          tcpSocket:
#            port: 2551
#          initialDelaySeconds: 30
#          timeoutSeconds: 30
