---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    name: frontend-service
    app: sclr
spec:
  clusterIP: None
  ports:
  - protocol: TCP
    name: akka-remote
    port: 2551
    targetPort: 2551
  selector:
    name: frontend

---
apiVersion: v1
kind: Service
metadata:
  name: http-service
  labels:
    name: http-service
    app: sclr
spec:
  ports:
  - protocol: TCP
    name: http-service
    port: 8080
    targetPort: 8080
  selector:
    name: frontend

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: frontend
      app: sclr
  template:
    metadata:
      labels:
        name: frontend
        app: sclr
    spec:
      containers:
      - name: frontend
        image: us.gcr.io/sclr-akka/frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2551
          name: akka-remote
        - containerPort: 8080
          name: http-service
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        env:
        - name: AKKA_REMOTING_BIND_HOST
          value: 'frontend-service.default.svc.cluster.local'
        - name: AKKA_REMOTING_BIND_PORT
          value: '2551'
        - name: AKKA_SEED_NODE
          value: 'akka.tcp://sclr@compute-0.compute-service.default.svc.cluster.local:2551'
        - name: DNS_RESOLVER
          value: 'async-dns'
        - name: RESOLVE_SRV
          value: 'true'
        - name: RESOLV_CONF
          value: 'on'
        - name: HTTP_HOST
          value: '0.0.0.0'
        - name: HTTP_PORT
          value: '8080'
