---
apiVersion: v1
kind: Service
metadata:
  name: manage-service
  labels:
    name: manage-service
    app: sclr
spec:
  clusterIP: None
  ports:
  - port: 2551
    protocol: TCP
    targetPort: 2551
  selector:
    name: manage

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: manage
spec:
  replicas: 1
  selector:
    matchLabels:
      name: manage
      app: sclr


  template:
    metadata:
      labels:
        name: manage
        app: sclr
    spec:
      containers:
      - name: manage
        image: us.gcr.io/sclr-akka/manage:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 2551
        env:
        - name: DATABASE_HOST
          value: sclr-mysql
        - name: DATABASE_USERNAME
          value: 'root'
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: password
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: FQDN
          value: "compute-service.default.svc.cluster.local"
        - name: AKKA_REMOTING_BIND_HOST
          value: "manage-service.default.svc.cluster.local"
        - name: AKKA_REMOTING_BIND_PORT
          value: '2551'
        - name: AKKA_SEED_NODE
          value: 'akka.tcp://sclr@compute-0.$(FQDN):2551'
        - name: HTTP_PORT
          value: '80'
