---
apiVersion: v1
kind: Service
metadata:
  name: manage-service
  labels:
    name: manage-service
    app: sclr
spec:
  clusterIP: None
  ports:
  - protocol: TCP
    name: akka-remote
    port: 2551
    targetPort: 2551
  selector:
    name: manage

---
apiVersion: v1
kind: Service
metadata:
  name: http-service
  labels:
    name: http-service
    app: sclr
spec:
  ports:
  - protocol: TCP
    name: http-service
    port: 8080
    targetPort: 8080
  selector:
    name: manage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manage
spec:
  replicas: 1
  selector:
    matchLabels:
      name: manage
      app: sclr
  template:
    metadata:
      labels:
        name: manage
        app: sclr
    spec:
      containers:
      - name: manage
        image: us.gcr.io/washu-seas-mltheory/sclr:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 2551
          name: akka-remote
        - containerPort: 8080
          name: http-service
        resources:
          limits:
            cpu: 3500m
            memory: 12G
        env:
        - name: DATABASE_HOST
          value: mysql-service
        - name: DATABASE_USERNAME
          value: 'root'
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: password
        - name: AKKA_REMOTING_BIND_HOST
          value: 'manage-service.default.svc.cluster.local'
        - name: AKKA_REMOTING_BIND_PORT
          value: '2551'
        - name: AKKA_SEED_NODES.0
          value: 'akka.tcp://sclr@manage-service.default.svc.cluster.local:2551'
        - name: AKKA_SEED_NODES.1
          value: 'akka.tcp://sclr@compute-0.compute-service.default.svc.cluster.local:2551'
        - name: AKKA_CLUSTER_ROLES.0
          value: 'manage'
        - name: DNS_RESOLVER
          value: 'async-dns'
        - name: RESOLVE_SRV
          value: 'true'
        - name: RESOLV_CONF
          value: 'on'
        - name: HTTP_HOST
          value: '0.0.0.0'
        - name: HTTP_PORT
          value: '8080'
