---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: manage
  labels:
    name: manage
    tier: akka
    app: sclr
spec:
  replicas: 1
  selector:
    matchLabels:
      name: manage
      tier: akka
      app: sclr
  template:
    metadata:
      labels:
        name: manage
        tier: akka
        app: sclr
    spec:
      containers:
      - name: manage
        image: us.gcr.io/sclr-akka/manage:latest
        imagePullPolicy: Never
        ports:
        - name: akka-remote
          containerPort: 2551
#        env:
#        - name: AKKA_REMOTING_BIND_HOST
#          value: ".local"
#        - name: AKKA_REMOTING_BIND_PORT
#          value: '2551'
#        - name: AKKA_SEED_NODE_0
#          value: 'akka.tcp://sclr@compute-0.local:2551'
#        - name: AKKA_SEED_NODE_1
#          value: 'akka.tcp://sclr@compute-0.local:2552'
#        - name: CLUSTER_MEMBERSHIP_ASK_TIMEOUT
#          value: '5000'
