---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: manage
  labels:
    name: manage
    app: sclr
spec:
  replicas: 1
  selector:
    matchLabels:
      name: manage
      app: sclr
  template:
    metadata:
      labels:
        name: manage
        app: sclr
    spec:
      containers:
      - name: manage
        image: us.gcr.io/sclr-akka/compute:latest
        imagePullPolicy: Never
        ports:
        - name: akka-remote
          containerPort: 2551
        env:
        - name: AKKA_REMOTING_BIND_PORT
          value: '2551'
        - name: AKKA_REMOTING_BIND_HOST
          value: "$HOSTNAME.sclr.default.svc.cluster.local"
        - name: AKKA_SEED_NODES
          value: 'compute-0.sclr.default.svc.cluster.local:2551'
        - name: CLUSTER_MEMBERSHIP_ASK_TIMEOUT
          value: '5000'
