apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    name: mysql-service
    app: sclr
spec:
  clusterIP: None
  ports:
    - port: 3306
  selector:
    name: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    name: mysql-pv-claim
    app: sclr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    name: mysql
    app: sclr
spec:
  selector:
    matchLabels:
      name: mysql
      app: sclr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: mysql
        app: sclr
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        args:
          - "--ignore-db-dir=lost+found"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: password
        resources:
          limits:
            cpu: 3000m
            memory: 6G
          requests:
            cpu: 1000m
            memory: 2G
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
