apiVersion: extensions/v1
kind: Deployment
metadata:
  name: compute
  labels:
    name: compute
    app: sclr
spec:
  replicas: 3
  template:
    metadata:
      name: compute
      labels:
        name: compute
    spec:
      containers:
      - name: compute
        image: us.gcr.io/sclr/compute:latest
        ports:
        - name: akka-remote
          containerPort: 2551
        env:
          - name: AKKA_THIS_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
