apiVersion: extensions/v1
kind: Deployment
metadata:
  name: manage
  labels:
    name: manage
    app: sclr
spec:
  replicas: 1
  template:
    metadata:
      name: manage
      labels:
        name: manage
    spec:
      containers:
      - name: manage
        image: us.gcr.io/sclr/sclr-manage:latest
        ports:
        - name: akka-remote
          containerPort: 2551
        env:
          - name: AKKA_THIS_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
