---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sclr-service
  name: sclr-service
spec:
  clusterIP: None
  ports:
  - port: 2551
    protocol: TCP
    targetPort: 2551
  selector:
    app: sclr-service
