---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sclr
spec:
  serviceName: sclr
  podManagementPolicy: Parallel
  replicas: 3
  template:
    metadata:
      labels:
        app: sclr
    spec:
      containers:
      - name: sclr
        image: szihai/sclr:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 2551
          name: akka-remote
        resources:
          limits:
            cpu: 250m
            memory: 384Mi
          requests:
            cpu: 250m
            memory: 384Mi
        env:
        - name: AKKA_ACTOR_SYSTEM_NAME
          value: sclr
        - name: AKKA_REMOTING_BIND_PORT
          value: '2551'
        - name: AKKA_REMOTING_BIND_HOST
          value: "$HOSTNAME.sclr.default.svc.cluster.local"
        - name: AKKA_SEED_NODES
          value: sclr-0.sclr.default.svc.cluster.local:2551,sclr-1.sclr.default.svc.cluster.local:2551
        - name: HTTP_HOST
          value: 0.0.0.0
        - name: HTTP_PORT
          value: '9000'
        - name: CLUSTER_MEMBERSHIP_ASK_TIMEOUT
          value: '5000'
        readinessProbe:
          tcpSocket:
            port: 2551
          initialDelaySeconds: 30
          timeoutSeconds: 30
